import { AdData, AdFormState, CampaignObjective, AdPlacement, BidStrategy } from './advertTypes';

export const campaignObjectives = [
  { value: 'Brand_Awareness' as CampaignObjective, label: 'Brand Awareness' },
  { value: 'Reach' as CampaignObjective, label: 'Reach' },
  { value: 'Traffic' as CampaignObjective, label: 'Traffic' },
  { value: 'Engagement' as CampaignObjective, label: 'Engagement' },
  { value: 'App_Installs' as CampaignObjective, label: 'App Installs' },
  { value: 'Video_Views' as CampaignObjective, label: 'Video Views' },
  { value: 'Lead_Generation' as CampaignObjective, label: 'Lead Generation' },
  { value: 'Conversions' as CampaignObjective, label: 'Conversions' },
];

export const adPlacements = [
  { value: 'Facebook_Feed' as AdPlacement, label: 'Feed' },
  { value: 'Instagram_Feed' as AdPlacement, label: 'Ticket Feed' },
  { value: 'Instagram_Stories' as AdPlacement, label: 'Stories' },
  { value: 'Facebook_Stories' as AdPlacement, label: 'Community' },
  { value: 'Messenger' as AdPlacement, label: 'Messenges' },
  { value: 'Audience_Network' as AdPlacement, label: 'Audience Network' },
  { value: 'Google_Search' as AdPlacement, label: 'Search' },
  { value: 'Google_Display' as AdPlacement, label: 'Display Network' },
  { value: 'YouTube' as AdPlacement, label: 'pop up' },
];

export const bidStrategies = [
  { value: 'Lowest_Cost' as BidStrategy, label: 'Lowest Cost' },
  { value: 'Cost_Cap' as BidStrategy, label: 'Cost Cap' },
  { value: 'Bid_Cap' as BidStrategy, label: 'Bid Cap' },
  { value: 'Target_Cost' as BidStrategy, label: 'Target Cost' },
];

export const interestCategories = [
  'Sports',
  'Football',
  'Basketball',
  'Tennis',
  'Cricket',
  'Gaming',
  'Entertainment',
  'Movies',
  'Music',
  'Technology',
  'Fashion',
  'Food',
  'Travel',
  'Business',
  'Finance',
  'Health',
  'Fitness',
  'Education',
  'Books',
  'Art',
  'Photography',
  'Cars',
  'Real Estate',
];

export const behaviorCategories = [
  'Frequent Travelers',
  'Online Shoppers',
  'Mobile Game Players',
  'Sports Fans',
  'Tech Early Adopters',
  'Luxury Shoppers',
  'Small Business Owners',
  'New Parents',
  'College Students',
  'Recently Moved',
  'Anniversary',
  'Birthday',
];

export const nigerianStates = [
  'Lagos',
  'Kano',
  'Kaduna',
  'Oyo',
  'Rivers',
  'Bayelsa',
  'Katsina',
  'Cross River',
  'Abia',
  'Adamawa',
  'Akwa Ibom',
  'Anambra',
  'Bauchi',
  'Benue',
  'Borno',
  'Delta',
  'Ebonyi',
  'Edo',
  'Ekiti',
  'Enugu',
  'Gombe',
  'Imo',
  'Jigawa',
  'Kebbi',
  'Kogi',
  'Kwara',
  'Nasarawa',
  'Niger',
  'Ogun',
  'Ondo',
  'Osun',
  'Plateau',
  'Sokoto',
  'Taraba',
  'Yobe',
  'Zamfara',
  'FCT',
];

export const initialAds: AdData[] = [
  {
    id: 1,
    title: 'Super Odds Weekend!',
    description: 'Promote your predictions and reach more users this weekend.',
    budget: '₦10,000',
    dailyBudget: '₦1,000',
    totalBudget: '₦10,000',
    status: 'Active',
    created: '2024-06-20',
    startDate: '2024-06-20',
    endDate: '2024-06-30',
    objective: 'Traffic',
    placements: ['Facebook_Feed', 'Instagram_Feed'],
    bidStrategy: 'Lowest_Cost',
    targeting: {
      demographics: {
        gender: 'All',
        ageRanges: ['18-24', '25-34', '35-44'],
        locations: [
          { type: 'Country', name: 'Nigeria' },
          { type: 'State', name: 'Lagos' },
        ],
        languages: ['English', 'Yoruba', 'Igbo', 'Hausa'],
      },
      interests: {
        categories: ['Sports', 'Football', 'Gaming'],
        keywords: ['football predictions', 'sports betting', 'odds'],
        behaviors: ['Sports Fans', 'Online Shoppers'],
      },
      customAudiences: ['Website Visitors', 'App Users'],
      lookalikePer: 1,
    },
    schedule: {
      enabled: true,
      timezone: 'Africa/Lagos',
      schedule: {
        monday: { enabled: true, startTime: '09:00', endTime: '22:00' },
        tuesday: { enabled: true, startTime: '09:00', endTime: '22:00' },
        wednesday: { enabled: true, startTime: '09:00', endTime: '22:00' },
        thursday: { enabled: true, startTime: '09:00', endTime: '22:00' },
        friday: { enabled: true, startTime: '09:00', endTime: '23:00' },
        saturday: { enabled: true, startTime: '08:00', endTime: '23:00' },
        sunday: { enabled: true, startTime: '08:00', endTime: '22:00' },
      },
    },
    impressions: 15420,
    clicks: 892,
    ctr: 5.79,
    cpc: 11.21,
    spent: 8750,
    conversions: 45,
  },
  {
    id: 2,
    title: 'Champions League Final Promo',
    description: 'Special ad for the Champions League final predictions.',
    budget: '₦5,000',
    dailyBudget: '₦500',
    totalBudget: '₦5,000',
    status: 'Paused',
    created: '2024-06-10',
    startDate: '2024-06-10',
    endDate: '2024-06-15',
    objective: 'Conversions',
    placements: ['Google_Search', 'YouTube'],
    bidStrategy: 'Target_Cost',
    bidAmount: '₦15',
    targeting: {
      demographics: {
        gender: 'All',
        ageRanges: ['18-24', '25-34', '35-44', '45-54'],
        locations: [{ type: 'Country', name: 'Nigeria' }],
        languages: ['English'],
      },
      interests: {
        categories: ['Sports', 'Football', 'Entertainment'],
        keywords: ['champions league', 'football final', 'predictions'],
        behaviors: ['Sports Fans', 'Tech Early Adopters'],
      },
      customAudiences: ['Past Customers'],
      lookalikePer: 2,
    },
    schedule: {
      enabled: false,
      timezone: 'Africa/Lagos',
      schedule: {
        monday: { enabled: true, startTime: '00:00', endTime: '23:59' },
        tuesday: { enabled: true, startTime: '00:00', endTime: '23:59' },
        wednesday: { enabled: true, startTime: '00:00', endTime: '23:59' },
        thursday: { enabled: true, startTime: '00:00', endTime: '23:59' },
        friday: { enabled: true, startTime: '00:00', endTime: '23:59' },
        saturday: { enabled: true, startTime: '00:00', endTime: '23:59' },
        sunday: { enabled: true, startTime: '00:00', endTime: '23:59' },
      },
    },
    impressions: 8340,
    clicks: 234,
    ctr: 2.81,
    cpc: 21.37,
    spent: 4200,
    conversions: 12,
  },
];

export const initialForm: AdFormState = {
  title: '',
  description: '',
  dailyBudget: '',
  totalBudget: '',
  startDate: '',
  endDate: '',
  image: null,
  objective: 'Traffic',
  placements: [],
  bidStrategy: 'Lowest_Cost',
  bidAmount: '',
  targeting: {
    demographics: {
      gender: 'All',
      ageRanges: [],
      locations: [],
      languages: [],
    },
    interests: {
      categories: [],
      keywords: [],
      behaviors: [],
    },
    customAudiences: [],
    lookalikePer: 1,
  },
  schedule: {
    enabled: false,
    timezone: 'Africa/Lagos',
    schedule: {
      monday: { enabled: true, startTime: '09:00', endTime: '22:00' },
      tuesday: { enabled: true, startTime: '09:00', endTime: '22:00' },
      wednesday: { enabled: true, startTime: '09:00', endTime: '22:00' },
      thursday: { enabled: true, startTime: '09:00', endTime: '22:00' },
      friday: { enabled: true, startTime: '09:00', endTime: '22:00' },
      saturday: { enabled: true, startTime: '09:00', endTime: '22:00' },
      sunday: { enabled: true, startTime: '09:00', endTime: '22:00' },
    },
  },
};